server:
  port: 8080
  error:
    include-message: always
demo-lol:
  lol:
    apikey: RGAPI-b9e72161-6612-44ea-b3e1-fad4de18bc25
    path:
      rotations: /lol/platform/v3/champion-rotations
      summoner:
        by-account: /lol/summoner/v4/summoners/by-account/{encryptedAccountId}
        by-name: /lol/summoner/v4/summoners/by-name/{summonerName}
        by-puuid: /lol/summoner/v4/summoners/by-puuid/{encryptedPUUID}
      spectator:
        active-games:
          by-summoner: /lol/spectator/v4/active-games/by-summoner/{encryptedSummonerId}
        featured-games: /lol/spectator/v4/featured-games
      status: /lol/status/v4/platform-data
      league:
        challenger-leagues:
          queue: /lol/league/v4/challengerleagues/by-queue/{queue}
        entries: 
          entries: /lol/league/v4/entries/{queue}/{tier}/{division}
          by-summoner: /lol/league/v4/entries/by-summoner/{encryptedSummonerId}
        grand-master-leagues:
          by-queue: /lol/league/v4/grandmasterleagues/by-queue/{queue}
        leagues:  /lol/league/v4/leagues/{leagueId}
        master-leagues:
          by-queue: /lol/league/v4/masterleagues/by-queue/{queue}        
  la1:
    url: https://la1.api.riotgames.com